// Expanded Antibiotic Database for Nigerian Context
export const getAntibioticsDatabase = () => {
  return [
    {
      id: 1,
      name: 'Amoxicillin',
      genericName: 'Amoxicillin',
      images: [
        '/amoxicillin-250mg-capsules_.jpg',
        '/Amoxicillin-500mg-caps-3-scaled.webp'
      ],
      commonBrands: ['Amoxytor', 'Ranmoxy', 'Amoxil', 'Amoxtrin'],
      forms: ['Capsules', 'Suspension', 'Tablets'],
      appearance: 'Red/white or red/yellow capsules',
      commonUses: [
        'Respiratory tract infections',
        'Ear infections',
        'Urinary tract infections',
        'Skin infections',
        'Dental infections'
      ],
      dosageGuidelines: '250-500mg every 8 hours',
      warnings: 'Complete full course. Tell doctor about penicillin allergies.',
      nigerianContext: 'Most commonly prescribed antibiotic. Available everywhere.',
      resistanceNote: 'Resistance growing - use only when appropriate'
    },
    {
      id: 2,
      name: 'Ciprofloxacin',
      genericName: 'Ciprofloxacin',
      images: ['/cipro_500mg.webp', '/cipro_750mg.webp'],
      commonBrands: ['Ciproflox', 'Ciprotab', 'Cipro', 'Sifral'],
      forms: ['Tablets', 'Capsules', 'Suspension', 'Eye/Ear drops', 'Injection'],
      appearance: 'Yellow/cream tablets',
      commonUses: ['Urinary tract infections', 'Typhoid fever', 'Bacterial diarrhea', 'Respiratory infections'],
      dosageGuidelines: '500-750mg every 12 hours',
      warnings: 'Avoid in children and pregnant women. May cause tendon problems.',
      nigerianContext: 'Essential for typhoid treatment. Multiple brands available.',
      resistanceNote: 'Typhoid resistance emerging - use CDC guidelines'
    },
    {
      id: 3,
      name: 'Metronidazole (Flagyl)',
      genericName: 'Metronidazole',
      images: ['/flagyl_200mg.webp', '/Flagyl-400mg-Tablets-Metronidazole-400mg-10-Tablets.jpg'],
      commonBrands: ['Flagyl', 'Metrogyl', 'Metro', 'Metrin'],
      forms: ['Tablets', 'Suspension', 'Injection', 'Pessaries'],
      appearance: 'White or yellow round tablets',
      commonUses: ['Amoebiasis and giardiasis', 'Bacterial vaginosis', 'Dental infections', 'H. pylori treatment'],
      dosageGuidelines: '200-400mg every 8 hours (7-14 days)',
      warnings: 'NEVER take with alcohol! Avoid in first trimester.',
      nigerianContext: 'Essential for parasitic infections. Part of amoebic dysentery treatment.',
      resistanceNote: 'Very effective - maintain compliance'
    },
    {
      id: 4,
      name: 'Azithromycin',
      genericName: 'Azithromycin',
      images: ['/Azithromycin-500mg-Tablets-3-Tablets-1-600x600.jpg', '/azithromycin_250mg.webp'],
      commonBrands: ['Zithromax', 'Azithrocin', 'Aziwin', 'Azamax'],
      forms: ['Tablets', 'Capsules', 'Suspension', 'Injection'],
      appearance: 'White/pink tablets, often in 3-day packs',
      commonUses: ['Respiratory infections', 'STIs', 'Skin infections', 'Typhoid (resistant strains)'],
      dosageGuidelines: '500mg day 1, then 250mg days 2-5 OR 3-day course',
      warnings: 'Take on empty stomach. May cause heart issues in susceptible people.',
      nigerianContext: 'Very popular due to short 3-day course. Increasing use for resistant typhoid.',
      resistanceNote: 'Reserve for resistant infections'
    },
    {
      id: 5,
      name: 'Ampiclox',
      genericName: 'Ampicillin + Cloxacillin',
      images: ['/Ampiclox_500mg.jpg', '/Ampiclox_250_250mg.webp'],
      commonBrands: ['Ampiclox', 'Ampilox'],
      forms: ['Capsules', 'Injection', 'Suspension'],
      appearance: 'Pink/black distinctive capsules',
      commonUses: ['Mixed infections', 'Post-surgical infections', 'Skin infections', 'Respiratory infections'],
      dosageGuidelines: '250-500mg every 6-8 hours',
      warnings: 'Penicillin allergy check. Complete full course.',
      nigerianContext: 'Second-line option. Popular combination in Nigeria.',
      resistanceNote: 'Moderate resistance - reserve use'
    },
    {
      id: 6,
      name: 'Septrin (Co-trimoxazole)',
      genericName: 'Sulfamethoxazole + Trimethoprim',
      images: ['/Septrinn.jfif', '/Septrin_suspension.webp'],
      commonBrands: ['Septrin', 'Bactrim', 'Cotrim', 'Sumetrim'],
      forms: ['Tablets', 'Suspension', 'Injection'],
      appearance: 'White tablets or orange/pink suspension',
      commonUses: ['UTIs', 'Respiratory infections', 'Traveler\'s diarrhea', 'PCP prophylaxis'],
      dosageGuidelines: '960mg every 12 hours',
      warnings: 'Drink plenty of water. Avoid if sulfa allergy.',
      nigerianContext: 'Essential for UTIs. Common suspension for children.',
      resistanceNote: 'Resistance increasing - limit use'
    },
    {
      id: 7,
      name: 'Tetracycline',
      genericName: 'Tetracycline Hydrochloride',
      images: ['/tetracyn-500mg-500x500.webp', '/tetracycline-tab_250mg.jpg'],
      commonBrands: ['Tetracyn', 'Tetrex', 'Tetravite'],
      forms: ['Capsules', 'Tablets', 'Suspension'],
      appearance: 'Red/black or yellow/pink capsules',
      commonUses: ['Acne', 'Respiratory infections', 'Cholera', 'Rickettsial infections'],
      dosageGuidelines: '250-500mg every 6 hours (empty stomach)',
      warnings: 'NEVER give to children <8 or pregnant women. Avoid dairy.',
      nigerianContext: 'Still used for cholera. Dentists avoid prescribing.',
      resistanceNote: 'Widespread resistance to many organisms'
    },
    {
      id: 8,
      name: 'Augmentin',
      genericName: 'Amoxicillin + Clavulanic Acid',
      images: ['/Augmentin_1g.jpg', '/Augmentin.jpeg'],
      commonBrands: ['Augmentin', 'Co-amoxiclav', 'Augmex', 'Clavamox'],
      forms: ['Tablets', 'Suspension', 'Injection'],
      appearance: 'Purple/blue boxes, white tablets',
      commonUses: ['Resistant infections', 'Respiratory infections', 'UTIs', 'Skin infections', 'Dental infections'],
      dosageGuidelines: '625mg every 8 hours OR 1g every 12 hours',
      warnings: 'Take with food. Complete full course.',
      nigerianContext: 'Premium antibiotic. Used for resistant infections.',
      resistanceNote: 'Reserve for beta-lactamase producing organisms'
    },
    {
      id: 9,
      name: 'Chloroquine & Chloroquine + Proguanil',
      genericName: 'Chloroquine Phosphate / Avloclor',
      images: [],
      commonBrands: ['Avloclor', 'Aralen', 'Chloroquine'],
      forms: ['Tablets', 'Injection', 'Syrup'],
      appearance: 'White tablets',
      commonUses: ['Malaria (now limited use)', 'Rheumatoid arthritis'],
      dosageGuidelines: '600mg stat, then 300mg at 6,24,48 hours',
      warnings: 'Resistance widespread. Use artemisinin combination now.',
      nigerianContext: 'DEPRECATED for malaria. Use ACT instead. Still available.',
      resistanceNote: 'High resistance - use artemisinin combinations'
    },
    {
      id: 10,
      name: 'Artemether/Artemisinin',
      genericName: 'Artemether or Artemisinin derivatives',
      images: [],
      commonBrands: ['Artesunate IV', 'Artemether IM', 'Artemether', 'Coartem (AL)'],
      forms: ['Injection', 'Tablets/Suspension combinations'],
      appearance: 'Varies by brand',
      commonUses: ['Severe malaria', 'Uncomplicated malaria (combinations)'],
      dosageGuidelines: 'SC/IM: 120mg/day x3 days. IV: 2.4mg/kg at 0,12,24h then daily',
      warnings: 'Use IV form for severe malaria. Switch to oral AL on improvement.',
      nigerianContext: 'FIRST-LINE for malaria. Almost all malaria caused by P.falciparum.',
      resistanceNote: 'Gold standard treatment. Maintain compliance'
    },
    {
      id: 11,
      name: 'Artemisinin + Lumefantrine',
      genericName: 'Artemether-Lumefantrine (AL)',
      images: [],
      commonBrands: ['Coartem', 'Ariplus', 'Artefan', 'Duocotex'],
      forms: ['Tablets (fixed combination)'],
      appearance: 'Blister packs with 6 tablets',
      commonUses: ['Uncomplicated malaria (oral)'],
      dosageGuidelines: 'Wt-based dosing: 2 doses on day 1, then 1 dose days 2-3',
      warnings: 'Take with fatty meal for absorption. Complete full course.',
      nigerianContext: 'FIRST-LINE for uncomplicated malaria. Widely available.',
      resistanceNote: 'Excellent efficacy. Maintain compliance to prevent resistance'
    },
    {
      id: 12,
      name: 'Dihydroartemisinin + Piperaquine',
      genericName: 'DHA + Piperaquine',
      images: [],
      commonBrands: ['Duocotex Plus', 'Eurartesim', 'Piperart'],
      forms: ['Tablets', 'Suspension'],
      appearance: 'Blister packs',
      commonUses: ['Malaria treatment (alternative to AL)'],
      dosageGuidelines: 'Wt-based: once daily x 3 days',
      warnings: 'Take with food. Longer half-life - watch for drug interactions.',
      nigerianContext: 'Alternative to AL. Longer acting - consider drug interactions.',
      resistanceNote: 'Good efficacy. Monitor for emerging resistance'
    },
    {
      id: 13,
      name: 'Chlorproguanil-Dapsone',
      genericName: 'Chlorproguanil + Dapsone',
      images: [],
      commonBrands: ['Deltaprim', 'Avoguanil'],
      forms: ['Tablets'],
      appearance: 'Blister packs',
      commonUses: ['Malaria prophylaxis and treatment'],
      dosageGuidelines: '1 tablet daily (prophylaxis) or wt-based x 3 (treatment)',
      warnings: 'Check for G6PD deficiency before dapsone use.',
      nigerianContext: 'Option for malaria. Increasing use due to cost.',
      resistanceNote: 'Moderate resistance emerging'
    },
    {
      id: 14,
      name: 'Quinine',
      genericName: 'Quinine Dihydrochloride',
      images: [],
      commonBrands: ['Quinine IV', 'Quinine IM'],
      forms: ['Injection (IV/IM)', 'Tablets (rare)'],
      appearance: 'Clear injection solution',
      commonUses: ['Severe malaria (alternative to artemisinin)', 'Nocturnal leg cramps'],
      dosageGuidelines: 'Loading: 20mg/kg IV infusion, then 10mg/kg 8-hourly',
      warnings: 'Hypoglycemia risk - monitor. NOT first-line now.',
      nigerianContext: 'Backup if artemisinin unavailable. Switch to AL when stable.',
      resistanceNote: 'Effective but second-line due to side effects'
    },
    {
      id: 15,
      name: 'Albendazole',
      genericName: 'Albendazole',
      images: [],
      commonBrands: ['Albenza', 'Alben', 'Albverm'],
      forms: ['Tablets', 'Suspension', 'Chewable'],
      appearance: 'White tablets or suspension',
      commonUses: ['Helminth infections (roundworm, hookworm, tapeworm)', 'Neurocysticercosis'],
      dosageGuidelines: '400mg once daily x 3 days (varies by infection)',
      warnings: 'Avoid in pregnancy (teratogenic). Monitor LFTs.',
      nigerianContext: 'Essential in areas with high worm burden. School deworming programs.',
      resistanceNote: 'Excellent efficacy - no resistance'
    },
    {
      id: 16,
      name: 'Mebendazole',
      genericName: 'Mebendazole',
      images: [],
      commonBrands: ['Vermox', 'Mebex', 'Pantelmin'],
      forms: ['Tablets', 'Suspension', 'Chewable'],
      appearance: 'White/pink tablets or suspension',
      commonUses: ['Roundworm, hookworm, whipworm', 'Pinworm (threadworm)'],
      dosageGuidelines: '100mg twice daily x 3 days (varies by infection)',
      warnings: 'Usually well-tolerated. Avoid in early pregnancy.',
      nigerianContext: 'Cheaper alternative. Available without prescription.',
      resistanceNote: 'Effective - widely available'
    },
    {
      id: 17,
      name: 'Praziquantel',
      genericName: 'Praziquantel',
      images: [],
      commonBrands: ['Biltricide', 'Prastel', 'Prazide'],
      forms: ['Tablets', 'Suspension'],
      appearance: 'White tablets',
      commonUses: ['Schistosomiasis', 'Other trematode infections'],
      dosageGuidelines: '20-30mg/kg/day in 2-3 divided doses x 1 day',
      warnings: 'Diarrhea common - transient. Take with water.',
      nigerianContext: 'Endemic in many Nigerian regions. Mass treatment campaigns.',
      resistanceNote: 'Very effective. Excellent compliance needed'
    },
    {
      id: 18,
      name: 'Iodine-based antiseptics',
      genericName: 'Povidone Iodine / Potassium Iodide',
      images: [],
      commonBrands: ['Betadine', 'Savlon', 'Lugol\'s Solution'],
      forms: ['Solution', 'Ointment', 'Spray', 'Swabs'],
      appearance: 'Brown solution or cream',
      commonUses: ['Wound disinfection', 'Skin sterilization', 'Gargling for sore throat'],
      dosageGuidelines: 'Topical use as needed',
      warnings: 'Avoid in iodine allergy. Some staining of skin/clothes.',
      nigerianContext: 'Ubiquitous in Nigerian healthcare. Essential first aid.',
      resistanceNote: 'Topical - no resistance'
    },
    {
      id: 19,
      name: 'Doxycycline',
      genericName: 'Doxycycline Hydrochloride',
      images: [],
      commonBrands: ['Doxycycline', 'Doxyvit', 'Atridox'],
      forms: ['Tablets', 'Capsules', 'Injection'],
      appearance: 'Yellow/orange capsules or white tablets',
      commonUses: ['Respiratory infections', 'STIs (chlamydia)', 'Lyme disease', 'Acne', 'Malaria prophylaxis'],
      dosageGuidelines: '100mg twice daily or 200mg daily',
      warnings: 'Photosensitivity - avoid sun exposure. Similar restrictions to tetracycline.',
      nigerianContext: 'Increasingly used. Better absorption than tetracycline.',
      resistanceNote: 'Emerging resistance in some organisms'
    },
    {
      id: 20,
      name: 'Ceftriaxone',
      genericName: 'Ceftriaxone Sodium',
      images: [],
      commonBrands: ['Rocephin', 'Ceftri', 'Tricef'],
      forms: ['Injection (IM/IV)'],
      appearance: 'Powder for reconstitution',
      commonUses: ['Meningitis', 'Severe respiratory infections', 'Gonorrhea', 'Sepsis'],
      dosageGuidelines: '1-2g IV/IM daily, divided doses or single. Meningitis: 2g q12h',
      warnings: 'IV preferring meningitis. Seek alternative if penicillin allergy (cross-reactivity 1-3%).',
      nigerianContext: 'Hospital formulary. Essential for meningitis management.',
      resistanceNote: 'Some resistance - use appropriately'
    }
  ]
}
